import { NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: Request) {
  try {
    const { to, subject, message, pdfBuffer, fileName } = await request.json();

    if (!to || !subject || !pdfBuffer) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Convert base64 string back to buffer if needed, but Resend accepts base64 content
    
    const data = await resend.emails.send({
      from: 'Invoice Generator <onboarding@resend.dev>', // Update this with your verified domain in production
      to: [to],
      subject: subject,
      html: `
        <div style="font-family: sans-serif; color: #333;">
          <p>${message.replace(/\n/g, '<br>')}</p>
          <hr />
          <p style="font-size: 12px; color: #666;">
            Generated by <strong>Invoice Generator</strong> via 3KPro
          </p>
        </div>
      `,
      attachments: [
        {
          filename: fileName || 'invoice.pdf',
          content: pdfBuffer, // Expecting base64 string (without data:application/pdf;base64, prefix preferably, or Resend handles it)
        },
      ],
    });

    if (data.error) {
       console.error("Resend Error:", data.error);
       return NextResponse.json({ error: data.error.message }, { status: 400 });
    }

    return NextResponse.json({ success: true, data });
  } catch (error) {
    console.error('Email sending failed:', error);
    return NextResponse.json(
      { error: 'Failed to send email' },
      { status: 500 }
    );
  }
}
