import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | XELORA",
  description:
    "Read XELORA's terms of service to understand the rules and guidelines for using our AI-powered social media management platform.",
  openGraph: {
    title: "Terms of Service | XELORA",
    description:
      "Read XELORA's terms of service to understand the rules and guidelines for using our platform.",
    url: "https://getxelora.com/terms",
  },
  alternates: {
    canonical: "https://getxelora.com/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-tron-darker py-16 px-4">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-tron-text mb-8">Terms of Service</h1>

        <div className="space-y-6 text-tron-text-muted">
          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using XELORA, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">2. Description of Service</h2>
            <p>
              XELORA is a social media management platform that provides AI-powered content generation, trend discovery, and multi-platform publishing capabilities for businesses and individuals.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">3. User Accounts</h2>
            <h3 className="text-xl font-medium text-tron-text mb-2">Registration</h3>
            <p className="mb-4">
              You must create an account to use XELORA. You agree to provide accurate, current information and keep your account secure.
            </p>

            <h3 className="text-xl font-medium text-tron-text mb-2">Account Responsibility</h3>
            <p>
              You are responsible for all activity that occurs under your account. You must immediately notify us of any unauthorized access.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">4. Social Media Connections</h2>
            <p className="mb-4">
              When you connect social media accounts to XELORA:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>You grant us permission to post content on your behalf</li>
              <li>You remain responsible for all content posted through our platform</li>
              <li>You must comply with each platform's terms of service</li>
              <li>You can revoke access at any time through account settings</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">5. Acceptable Use</h2>
            <p className="mb-4">You agree NOT to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Post illegal, harmful, or offensive content</li>
              <li>Spam or harass others</li>
              <li>Violate intellectual property rights</li>
              <li>Use the service for unauthorized commercial purposes</li>
              <li>Attempt to circumvent security measures</li>
              <li>Reverse engineer or copy our software</li>
              <li>Use automated tools to scrape our service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">6. Content Ownership</h2>
            <h3 className="text-xl font-medium text-tron-text mb-2">Your Content</h3>
            <p className="mb-4">
              You retain ownership of all content you create or upload. By using our service, you grant us a license to store, display, and process your content solely to provide the service.
            </p>

            <h3 className="text-xl font-medium text-tron-text mb-2">AI-Generated Content</h3>
            <p>
              Content generated by our AI tools is provided as-is. You are responsible for reviewing and editing AI-generated content before publishing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">7. Subscription and Payment</h2>
            <p className="mb-4">
              XELORA offers subscription-based pricing with different tiers:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Subscriptions renew automatically unless cancelled</li>
              <li>Payment is processed through Stripe</li>
              <li>Refunds are provided according to our refund policy</li>
              <li>We reserve the right to modify pricing with notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">8. Service Availability</h2>
            <p>
              We strive to maintain service availability but do not guarantee uninterrupted access. We may perform maintenance, updates, or experience outages beyond our control.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">9. Termination</h2>
            <p className="mb-4">
              We may suspend or terminate your account if you:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Violate these Terms of Service</li>
              <li>Engage in fraudulent activity</li>
              <li>Fail to pay subscription fees</li>
              <li>Request account deletion</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">10. Disclaimers</h2>
            <p className="mb-4">
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Accuracy of AI-generated content</li>
              <li>Success of social media posts</li>
              <li>Uninterrupted service availability</li>
              <li>Compatibility with all platforms</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">11. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, XELORA SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">12. Changes to Terms</h2>
            <p>
              We may modify these Terms of Service at any time. Continued use of the service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">13. Governing Law</h2>
            <p>
              These Terms shall be governed by the laws of the jurisdiction where 3K Pro Services operates, without regard to conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-tron-text mb-4">14. Contact</h2>
            <p>
              For questions about these Terms, contact us at:
            </p>
            <p className="mt-2">
              Email: support@getxelora.com<br />
              Website: https://getxelora.com
            </p>
          </section>

          <p className="text-sm text-tron-text-muted mt-8 pt-8 border-t border-tron-cyan/20">
            Last Updated: November 24, 2024
          </p>
        </div>
      </div>
    </div>
  );
}
