from datetime import datetime, timedelta
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from ...db import get_db
from ...models.domain import Commitment, Task, TaskPlatform
from ...services.asana_service import AsanaService
from ...services.linear_service import LinearService
from ...services.slack_service import SlackService

router = APIRouter(prefix="/integrations", tags=["integrations"])

@router.post("/asana/export/{commitment_id}")
async def export_commitment_to_asana(commitment_id: int, db: AsyncSession = Depends(get_db)):
    """
    Export a specific commitment to Asana as a task.
    """
    # 1. Fetch Commitment
    result = await db.execute(select(Commitment).where(Commitment.id == commitment_id))
    commitment = result.scalar_one_or_none()
    
    if not commitment:
        raise HTTPException(status_code=404, detail="Commitment not found")

    # 2. Check if already exported (optional check, but good for idempotency)
    # For MVP we might allow duplicates or check existing tasks relation
    # Let's simple check:
    # existing = await db.execute(select(Task).where(Task.commitment_id == commitment_id, Task.platform == TaskPlatform.ASANA))
    # ... logic skipped for brevity, allowing re-export

    # 3. Call Asana Service
    asana_service = AsanaService()
    
    # Format notes
    notes = f"Generated by PactPull\n\nCommitment: {commitment.description}\nAssignee (Text): {commitment.assignee}\nConfidence: {commitment.confidence_score}"
    
    task_data = await asana_service.create_task(
        name=commitment.description[:100], # Asana names shouldn't be too huge
        notes=notes,
        due_on=commitment.due_date_text
    )

    if not task_data:
        raise HTTPException(status_code=502, detail="Failed to create task in Asana")

    # 4. Save Task Record
    new_task = Task(
        commitment_id=commitment.id,
        platform=TaskPlatform.ASANA,
        external_task_id=task_data.get("gid"),
        external_url=task_data.get("permalink_url"),
        status="created"
    )
    
    db.add(new_task)
    await db.commit()
    await db.refresh(new_task)

    return {"status": "success", "task_id": new_task.id, "asana_gid": new_task.external_task_id}

@router.post("/linear/export/{commitment_id}")
async def export_commitment_to_linear(commitment_id: int, db: AsyncSession = Depends(get_db)):
    """
    Export a specific commitment to Linear as an issue.
    """
    # 1. Fetch Commitment
    result = await db.execute(select(Commitment).where(Commitment.id == commitment_id))
    commitment = result.scalar_one_or_none()
    
    if not commitment:
        raise HTTPException(status_code=404, detail="Commitment not found")

    # 2. Call Linear Service
    linear_service = LinearService()
    
    # Format description
    description = f"Generated by PactPull\n\n**Commitment:** {commitment.description}\n**Assignee:** {commitment.assignee}\n**Due Date:** {commitment.due_date_text}\n**Confidence:** {commitment.confidence_score}"
    
    issue_data = await linear_service.create_issue(
        title=commitment.description[:80],
        description=description
    )

    if not issue_data:
        raise HTTPException(status_code=502, detail="Failed to create issue in Linear")

    # 3. Save Task Record
    new_task = Task(
        commitment_id=commitment.id,
        platform=TaskPlatform.LINEAR,
        external_task_id=issue_data.get("id"),
        external_url=issue_data.get("url"),
        status="created"
    )
    
    db.add(new_task)
    await db.commit()
    await db.refresh(new_task)

    return {"status": "success", "task_id": new_task.id, "linear_id": new_task.external_task_id, "url": new_task.external_url}

@router.post("/slack/digest")
async def send_daily_digest(db: AsyncSession = Depends(get_db)):
    """
    Trigger a daily digest of recent commitments to Slack.
    """
    # 1. Fetch recent commitments (last 24 hours)
    since_time = datetime.utcnow() - timedelta(hours=24)
    result = await db.execute(
        select(Commitment)
        .where(Commitment.created_at >= since_time)
        .order_by(Commitment.confidence_score.desc())
    )
    commitments = result.scalars().all()
    
    if not commitments:
        return {"status": "skipped", "message": "No new commitments found in the last 24h"}

    # 2. Format Message Blocks
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "📅 Daily Commitment Digest",
                "emoji": True
            }
        },
        {
            "type": "divider"
        }
    ]

    for c in commitments:
        # Determine icon based on confidence
        icon = "🟢" if (c.confidence_score or 0) > 0.8 else "🟡" if (c.confidence_score or 0) > 0.5 else "🔴"
        
        assignee_text = f"*Assignee:* {c.assignee}" if c.assignee else "*Assignee:* Unassigned"
        due_text = f" | *Due:* {c.due_date_text}" if c.due_date_text else ""
        
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"{icon} *{c.description}*\n{assignee_text}{due_text}"
            }
        })

    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": f"Found {len(commitments)} new commitments | Generated by PactPull"
            }
        ]
    })

    # 3. Send via Slack Service
    slack_service = SlackService()
    success = await slack_service.send_message(
        text=f"Daily Digest: {len(commitments)} new commitments found.",
        blocks=blocks
    )

    if not success:
        raise HTTPException(status_code=502, detail="Failed to send Slack digest")

    return {"status": "success", "count": len(commitments)}
