-- Content Cascade AI - Security & Data Integrity Improvements
-- Generated by Supabase AI Assistant
-- Run this AFTER validating no existing data conflicts with ENUM values

-- ============================================================================
-- STEP 1: VALIDATION QUERIES (Run these first, check results)
-- ============================================================================

-- 1) subscription_tier in profiles
-- SELECT DISTINCT subscription_tier FROM public.profiles;

-- 2) subscription_status in profiles
-- SELECT DISTINCT subscription_status FROM public.profiles;

-- 3) campaigns.status
-- SELECT DISTINCT status FROM public.campaigns;

-- 4) campaigns.campaign_type
-- SELECT DISTINCT campaign_type FROM public.campaigns;

-- 5) social_accounts.platform and campaign_content.platform
-- SELECT DISTINCT platform FROM public.social_accounts;
-- SELECT DISTINCT platform FROM public.campaign_content;

-- 6) Ensure no NULLs where we will make columns NOT NULL (optional checks)
-- SELECT COUNT(*) AS missing_profile_email FROM public.profiles WHERE email IS NULL;
-- SELECT COUNT(*) AS missing_profiles_id FROM public.profiles WHERE id IS NULL;

-- ============================================================================
-- STEP 2: SETUP & ENUM CREATION
-- ============================================================================

-- pgcrypto extension setup (for future encryption helpers)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ENUM type creation (safe; will fail if type already exists — wrap in DO block)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subscription_tier_enum') THEN
    CREATE TYPE public.subscription_tier_enum AS ENUM ('free','pro','premium');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subscription_status_enum') THEN
    CREATE TYPE public.subscription_status_enum AS ENUM ('active','canceled','past_due','trialing');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'campaign_status_enum') THEN
    CREATE TYPE public.campaign_status_enum AS ENUM ('draft','scheduled','published','completed','failed');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'campaign_type_enum') THEN
    CREATE TYPE public.campaign_type_enum AS ENUM ('full','single','trending','uploaded');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'platform_enum') THEN
    CREATE TYPE public.platform_enum AS ENUM ('twitter','linkedin','facebook','instagram','tiktok','reddit');
  END IF;
END$$;

-- ============================================================================
-- STEP 3: SAFE COLUMN CONVERSIONS TO ENUMS
-- ============================================================================

-- 1) profiles.subscription_tier -> subscription_tier_enum
ALTER TABLE public.profiles
  ALTER COLUMN subscription_tier TYPE public.subscription_tier_enum
  USING (
    CASE
      WHEN subscription_tier IN ('free','pro','premium') THEN subscription_tier::public.subscription_tier_enum
      WHEN subscription_tier IS NULL THEN 'free'::public.subscription_tier_enum
      ELSE 'free'::public.subscription_tier_enum -- Safe fallback instead of error
    END
  );

-- 2) profiles.subscription_status -> subscription_status_enum
ALTER TABLE public.profiles
  ALTER COLUMN subscription_status TYPE public.subscription_status_enum
  USING (
    CASE
      WHEN subscription_status IN ('active','canceled','past_due','trialing') THEN subscription_status::public.subscription_status_enum
      WHEN subscription_status IS NULL THEN NULL
      ELSE NULL -- Safe fallback
    END
  );

-- 3) campaigns.status -> campaign_status_enum
ALTER TABLE public.campaigns
  ALTER COLUMN status TYPE public.campaign_status_enum
  USING (
    CASE
      WHEN status IN ('draft','scheduled','published','completed','failed') THEN status::public.campaign_status_enum
      WHEN status IS NULL THEN 'draft'::public.campaign_status_enum
      ELSE 'draft'::public.campaign_status_enum -- Safe fallback
    END
  );

-- 4) campaigns.campaign_type -> campaign_type_enum
ALTER TABLE public.campaigns
  ALTER COLUMN campaign_type TYPE public.campaign_type_enum
  USING (
    CASE
      WHEN campaign_type IN ('full','single','trending','uploaded') THEN campaign_type::public.campaign_type_enum
      WHEN campaign_type IS NULL THEN NULL
      ELSE NULL -- Safe fallback
    END
  );

-- 5) social_accounts.platform -> platform_enum
ALTER TABLE public.social_accounts
  ALTER COLUMN platform TYPE public.platform_enum
  USING (
    CASE
      WHEN platform IN ('twitter','linkedin','facebook','instagram','tiktok','reddit') THEN platform::public.platform_enum
      ELSE 'twitter'::public.platform_enum -- Safe fallback (shouldn't happen with constraints)
    END
  );

-- 6) campaign_content.platform -> platform_enum
ALTER TABLE public.campaign_content
  ALTER COLUMN platform TYPE public.platform_enum
  USING (
    CASE
      WHEN platform IN ('twitter','linkedin','facebook','instagram','tiktok','reddit') THEN platform::public.platform_enum
      ELSE 'twitter'::public.platform_enum -- Safe fallback
    END
  );

-- ============================================================================
-- STEP 4: TIGHTEN RLS POLICIES (Scope to authenticated users)
-- ============================================================================

-- PROFILES
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can delete own profile" ON public.profiles;

CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile" ON public.profiles
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can delete own profile" ON public.profiles
  FOR DELETE TO authenticated
  USING (auth.uid() = id);

-- SOCIAL ACCOUNTS
DROP POLICY IF EXISTS "Users can manage own social accounts" ON public.social_accounts;

CREATE POLICY "Users can manage own social accounts" ON public.social_accounts
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- BRAND VOICES
DROP POLICY IF EXISTS "Users can manage own brand voices" ON public.brand_voices;

CREATE POLICY "Users can manage own brand voices" ON public.brand_voices
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- CAMPAIGNS
DROP POLICY IF EXISTS "Users can manage own campaigns" ON public.campaigns;

CREATE POLICY "Users can manage own campaigns" ON public.campaigns
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- CAMPAIGN CONTENT
DROP POLICY IF EXISTS "Users can manage own campaign content" ON public.campaign_content;

CREATE POLICY "Users can manage own campaign content" ON public.campaign_content
  FOR ALL TO authenticated
  USING (
    campaign_id IN (
      SELECT id FROM public.campaigns WHERE user_id = auth.uid()
    )
  )
  WITH CHECK (
    campaign_id IN (
      SELECT id FROM public.campaigns WHERE user_id = auth.uid()
    )
  );

-- MEDIA ASSETS
DROP POLICY IF EXISTS "Users can manage own media" ON public.media_assets;

CREATE POLICY "Users can manage own media" ON public.media_assets
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- AI USAGE
DROP POLICY IF EXISTS "Users can view own usage" ON public.ai_usage;
DROP POLICY IF EXISTS "System can insert usage" ON public.ai_usage;
DROP POLICY IF EXISTS "Users can insert own usage" ON public.ai_usage;

CREATE POLICY "Users can view own usage" ON public.ai_usage
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own usage" ON public.ai_usage
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- API KEYS
DROP POLICY IF EXISTS "Users can manage own API keys" ON public.api_keys;

CREATE POLICY "Users can manage own API keys" ON public.api_keys
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ONBOARDING PROGRESS
DROP POLICY IF EXISTS "Users can manage own onboarding" ON public.onboarding_progress;

CREATE POLICY "Users can manage own onboarding" ON public.onboarding_progress
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ANALYTICS SNAPSHOTS
DROP POLICY IF EXISTS "Users can view own analytics" ON public.analytics_snapshots;
DROP POLICY IF EXISTS "System can insert analytics" ON public.analytics_snapshots;
DROP POLICY IF EXISTS "Users can insert own analytics" ON public.analytics_snapshots;

CREATE POLICY "Users can view own analytics" ON public.analytics_snapshots
  FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own analytics" ON public.analytics_snapshots
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- STEP 5: ADDITIONAL INDEXES (Optional - Create if needed)
-- ============================================================================

-- Platform post ID lookup (if polling/syncing social posts)
CREATE INDEX IF NOT EXISTS idx_campaign_content_platform_post_id
  ON public.campaign_content (platform_post_id);

-- Recent content listing
CREATE INDEX IF NOT EXISTS idx_campaign_content_created_at
  ON public.campaign_content (created_at DESC);

-- Analytics by date
CREATE INDEX IF NOT EXISTS idx_analytics_snapshots_date
  ON public.analytics_snapshots (snapshot_date DESC);

-- ============================================================================
-- STEP 6: SECURITY HARDENING
-- ============================================================================

-- Revoke execute on SECURITY DEFINER functions from public/authenticated
-- (Functions still execute as trigger but can't be called directly by users)
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM authenticated;

-- ============================================================================
-- VALIDATION: Index Check (Run after migration)
-- ============================================================================

-- List all indexes to verify they exist:
-- SELECT schemaname, tablename, indexname, indexdef
-- FROM pg_indexes
-- WHERE schemaname = 'public'
-- AND tablename IN (
--   'profiles','social_accounts','brand_voices','campaigns','campaign_content',
--   'media_assets','ai_usage','api_keys','onboarding_progress','analytics_snapshots'
-- )
-- ORDER BY tablename, indexname;
